version: "3"

networks:
  my-network:
    driver: bridge

services:
  service1:
    image: nginx
    container_name: nginx-container1
    networks:
      - my-network

  service2:
    image: nginx
    container_name: nginx-container2
    networks:
      - my-network
